#ifndef _FILES_FLAGS
#define _FILES_FLAGS

#define FILES_FLAG_RECURSIVE (0x1)
#define FILES_FLAG_FOLLOW_LINKS (0x2)
#define FILES_FLAG_SKIP_HIDDEN_DIRS (0x4)
#define FILES_FLAG_SKIP_HIDDEN_FILES (0x8)

#endif
